# SPDX-License-Identifier: GPL-2.0-or-later

load("//build/kernel/kleaf:kernel.bzl", "ddk_module")

# Convenience variables (to reduce repetition)

panel_deps = [
    "//common:all_headers_aarch64",
    "//private/google-modules/display/common:ddk_headers",
    "//private/google-modules/display/common/gs_panel",
]

panel_visibility = [
    "//private/devices/google:__subpackages__",
]

# Note: please add additional drivers as separate ddk modules

ddk_module(
    name = "panel-gs-tg4a",
    srcs = [
        "panel-gs-tg4a.c",
    ],
    out = "panel-gs-tg4a.ko",
    kernel_build = "//private/google-modules/soc/gs:gs_kernel_build",
    visibility = panel_visibility,
    deps = panel_deps,
)

ddk_module(
    name = "panel-gs-tg4b",
    srcs = [
        "panel-gs-tg4b.c",
    ],
    out = "panel-gs-tg4b.ko",
    kernel_build = "//private/google-modules/soc/gs:gs_kernel_build",
    visibility = panel_visibility,
    deps = panel_deps,
)

ddk_module(
    name = "panel-gs-tg4c",
    srcs = [
        "panel-gs-tg4c.c",
    ],
    out = "panel-gs-tg4c.ko",
    kernel_build = "//private/google-modules/soc/gs:gs_kernel_build",
    visibility = panel_visibility,
    deps = panel_deps,
)
